Areas/Admin/Models/ProductInformation/ItemProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShopMVC.Areas.Admin.Models.ProductInformation
{
    public class ItemProduct
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Category")]
        public string Category { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Price")]
        public decimal Price { get; set; }
    }
}

Areas/Admin/Controllers/ItemProductController.cs
using CoffeeShopMVC.Areas.Admin.Models.ProductInformation;
using CoffeeShopMVC.Areas.Admin.Repositories.DTO;
using CoffeeShopMVC.Areas.Admin.Services;
using CoffeeShopMVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShopMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ItemProductController : Controller
    {
        private readonly ItemProductServices _itemProductService;

        public ItemProductController(ItemProductServices itemProductServices)
        {
            _itemProductService = itemProductServices;
        }

        // GET: Admin/ItemProduct/Index
        public async Task<IActionResult> Index()
        {
            var itemProduct = (await _itemProductService.GetItemProductDTO()).Value;

            return View(itemProduct);
        }

        // GET: Admin/ItemProduct/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Category,Name,Price")] ItemProduct model)
        {
            if (ModelState.IsValid)
            {
                var isPosted = await _itemProductService.PostItemProduct(model);

                if (isPosted.Value) return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Admin/ItemProduct/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var itemProduct = await _itemProductService.GetByIdItemProductDTO(id);

            if (itemProduct.Value == null) return NotFound();

            return View(itemProduct.Value);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Category,Name,Price")] ItemProduct model)
        {
            if (id != model.ID) return NotFound();

            if (ModelState.IsValid)
            {
                var isUpdated = await _itemProductService.EditItemProduct(id, model);

                if (isUpdated.Value) return RedirectToAction(nameof(Index));
            }

            var itemProductDTO = new ItemProductDTO()
            {
                ID = model.ID,
                Category = model.Category,
                Name = model.Name,
                Price = model.Price
            };

            return View(itemProductDTO);
        }

        // GET: Admin/ItemProduct/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var itemProduct = await _itemProductService.GetByIdItemProductDTO(id);

            return View(itemProduct.Value);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("ID,Category,Name,Price")] ItemProduct model)
        {
            if (id != model.ID) return NotFound();

            var isDeleted = await _itemProductService.DeleteItemProduct(id, model);

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Admin/Views/ItemProduct/Create.cshtml
@model CoffeeShopMVC.Areas.Admin.Models.ProductInformation.ItemProduct
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Create Item Product</h1>
<hr />
<div class="row">
    <div class="col offset-4 col-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control">
                    <option value="">--- Select Category ---</option>
                    <option value="Drinks">Drinks</option>
                    <option value="Food">Food</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/ItemProduct/Delete.cshtml
@model CoffeeShopMVC.Areas.Admin.Repositories.DTO.ItemProductDTO
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/ItemProduct/Edit.cshtml
@model CoffeeShopMVC.Areas.Admin.Repositories.DTO.ItemProductDTO
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Edit Item Product</h1>
<hr />
<div class="row">
    <div class="col offset-4 col-4">
        <form asp-action="Edit" asp-route-id="ID">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="Category" class="form-control">
                    <option value="">--- Select Category ---</option>
                    <option value="Drinks">Drinks</option>
                    <option value="Food">Food</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/ItemProduct/Index.cshtml
@model IEnumerable<CoffeeShopMVC.Areas.Admin.Repositories.DTO.ItemProductDTO> 
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container row p-0 m-0">
    <div class="col-9">
        <h1>Item Product</h1>
    </div>
    <div class="col-3">
      
        <a type="button" class="btn btn-primary form-control" asp-area="Admin" asp-controller="ItemProduct" asp-action="Create">
            Create
        </a>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model) { 
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="ItemProduct" asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-area="Admin" asp-controller="ItemProduct" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>